### PR TITLE
Change the lexer to accept more complex identifiers, add rust tests

### LINKED ISSUE #57: Query Syntax can not handle complex service names.
The lexer panics when dealing with unknown characters in the service string. For example:
```bash
thread 'main' panicked at 'Unrecognized token string: -v1,', src/lexer.rs:34:18                                                 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace  
```
It is unwieldy to adjust the service names. Ideally, the lexer should be able to distinguish between string names and tokens.

### PR DESCRIPTION
**Pull request by fruffy**
This pull requests add tests for the rust queries and also changes the lexer slightly to accept identifier names with dashes. These identifier names have to be encapsulated in quotes. Fairly new to Rust, so I am sure there are better ways to do this.

Now with every pull request, all the queries will be compiled and tested.
Fixes #57.

Edit: The lexer still has some problems. Needs work.

### CODE REVIEW

File: example_queries/breadth_histogram_filter.cc [hunk 1]
```diff
@@ -230,7 +230,7 @@ void BidiContext::onResponseHeadersInbound() {
     LOG_WARN("x-wasm-property: " + properties_joined);
   }
 
-  if (root_->getWorkloadName() == "productpagev1") {
+  if (root_->getWorkloadName() == ""productpage-v1"") {
```
Comment (anirudhSK) [inline example_queries/breadth_histogram_filter.cc:233]: Why are there two sets of double quotes here?

File: example_queries/height_histogram_filter.cc [hunk 2]
```diff
@@ -230,7 +230,7 @@ void BidiContext::onResponseHeadersInbound() {
     LOG_WARN("x-wasm-property: " + properties_joined);
   }
 
-  if (root_->getWorkloadName() == "productpagev1") {
+  if (root_->getWorkloadName() == ""productpage-v1"") {
```
Comment (anirudhSK) [inline example_queries/height_histogram_filter.cc:233]: Same comment as above.

**Review by anirudhSK — CHANGES_REQUESTED** [review]

File: example_queries/breadth_histogram_filter.cc (hunk 1 above)
Comment (fruffy) [reply example_queries/breadth_histogram_filter.cc:233]: Yeah this is a tricky problem, which I have not been able to properly solve yet. Essentially, for a query like: 

`MATCH n-->m: e, WHERE a.service_name == "productpage-v1", RETURN count,`

You would like to get the text between the quotes as identifier. Ideally, the strings can be removed with a `replace` call after the token has been classified as identifier. Simple and fairly efficient. However,  I have not been able to get this past the borrow checker yet. Probably, for good reason, since `replace` allocates a new string. 

The second option is to prune the strings directly using Regex, but this has also problems. First, Rust does not seem to support lookahead Regex, so you are always forced to use two capture groups and choose the capture that does not have the strings with it. Second, even if you have the version without strings you still need to classify it as an identifier. There you need to distinguish between tokens, keywords, and actual identifiers to avoid conflict. One possibility is to augment the `get_single_token` function with information whether the passed `tok_str` used to have string wrappers or not.

I prefer option 1 since it is cleaner but it does not seem possible. Will try to get this done before the meeting.

Comment (anirudhSK) [reply example_queries/breadth_histogram_filter.cc:233]: OK, thanks for the explanation; that helps.

1. Stepping back a few levels up, do we really need to support hyphens in identifier names? Not many languages support that. 

2. If we do decide to support hyphens in identifier names, let's go with the current double double-quotes strategy. The double double quotes at least makes it clear that the string within the inner double quotes is a literal (and not say productpage minus v1). If we use the double double-quotes strategy, do we still need the replace/regex options you described above?

Comment (fruffy) [reply example_queries/breadth_histogram_filter.cc]: Regarding point 1 hyphens seem to be fairly common in Kubernetes names and are explicitly allowed. The pattern for names is `[a-z0-9]([-a-z0-9]*[a-z0-9])?` according to [this](https://stackoverflow.com/a/51724905) code. 

I pushed an approach that works reasonable well for now.

**Review by anirudhSK — APPROVED** [review]
